"""Integration with the supplied codebase, preserving its signal scaling and UQ.

There is no synthetic learned covariance and no replacement UQ formula here.
"""
import copy
import random
from types import SimpleNamespace
import numpy as np


def generate_case(case,system,trials):
    from src.signal_creation import Samples
    from src.system_model import SystemModelParams
    config=copy.deepcopy(system);config['snr']=case['snr_parameter']
    rho=case['rho_override']
    if rho is not None:
        if config.get('modulation','Gaussian')!='Gaussian':
            raise ValueError('The continuous-coherence experiment requires Gaussian source symbols; use native coherent/non-coherent cases for other modulations.')
        config['signal_nature']='non-coherent'
    params=SystemModelParams().set_params_from_json({'system_model':config})
    generator=Samples(params)
    generator.set_doa([case['theta_anchor_deg'],case['theta_moving_deg']])
    state=np.random.get_state()
    np.random.seed(case['test_seed'])
    x=np.empty((trials,config['N'],config['T']),dtype=np.complex64)
    signal_energy=np.zeros(2);noise_energy=0.;cross=0j
    try:
        for i in range(trials):
            raw,s,a,v=generator.samples_creation(noise_mean=0,noise_variance=1,signal_mean=0,signal_variance=1)
            if rho is not None:
                s=s.copy();s[1]=rho*s[0]+np.sqrt(max(0.,1-rho*rho))*s[1]
            if case['power_imbalance_db']:
                s=s.copy();s[1]*=10**(-case['power_imbalance_db']/20)
            x[i]=raw if rho is None and case['power_imbalance_db']==0 else a@s+v
            signal_energy+=np.mean(np.abs(s)**2,axis=1)
            noise_energy+=np.mean(np.abs(v)**2)
            cross+=np.mean(s[0]*s[1].conj())
    finally:np.random.set_state(state)
    return x,dict(realized_source_snr_anchor_db=float(10*np.log10(signal_energy[0]/noise_energy)),
                  realized_source_snr_moving_db=float(10*np.log10(signal_energy[1]/noise_energy)),
                  realized_waveform_correlation=float(abs(cross)/np.sqrt(np.prod(signal_energy))))


class NativePredictor:
    def __init__(self,target,config,config_path,args,device):
        import torch
        from src.uncertainty_block import UncertaintyEstimation
        self.torch=torch;self.args=args;self.device=device;self.target=target
        self.system=config['subarray_config'][0]['system_model']
        n,t,m=[self.system[k] for k in ['N','T','M']]
        self.model=None
        if target['model_type']=='multi_subarray':
            from src.multi_subarrays_model import MultiSubarraysModel
            self.model=MultiSubarraysModel(sensors_positions=np.array([[0.,0.]]),
                 multi_model_configuration=str(config_path),args=SimpleNamespace(train_doa_only=True)).to(device)
            self.model.estimate_uncertainty=True;
            self.model.enable_full_covariance_estimation()
            for block in self.model.uncertainty_pred:block.chunk_size=args.uq_chunk_size
        elif target['model_type']=='data_driven_complex':
            from src.models import DataDrivenComplexNet
            self.model=DataDrivenComplexNet(N=n,T=t,tau=args.tau,M=m).to(device)
        elif target['model_type']=='transmusic':
            from src.transmusic import TransMUSIC
            self.model=TransMUSIC(num_antennas=n,num_sources=m,num_angle_bins=args.num_angle_bins,d_spacing=.5).to(device)
        else:
            self.uq=UncertaintyEstimation(signal_shape=t,chunk_size=args.uq_chunk_size).to(device)
        if self.model is not None:
            # Native trainer saves optimizer and RNG metadata as well as tensors.
            # Use only trusted checkpoints generated by your own trainer, as test.py does.
            checkpoint=torch.load(target['checkpoint'],map_location=device,weights_only=False)
            if 'model_state_dict' not in checkpoint:raise KeyError('Expected native trainer checkpoint[model_state_dict].')
            state=checkpoint['model_state_dict']
            self.model.load_state_dict(state,strict=True)
            self.model.eval()
        self._first=True

    def __call__(self,x):
        torch=self.torch
        from src.criterions import model_output_to_covariance_rad2
        preds=[];covs=[]
        with torch.no_grad():
            for start in range(0,len(x),self.args.batch_size):
                xx=torch.as_tensor(x[start:start+self.args.batch_size],dtype=torch.complex64,device=self.device)
                batch=len(xx)
                if self.model is None:
                    # Same centered sample covariance convention as native test.py,
                    # but use predicted angles (not GT) and request FULL covariance.
                    from src.models import esprit_batched
                    xc=xx-xx.mean(dim=-1,keepdim=True)
                    rx=xc@xc.conj().transpose(-1,-2)/(xx.shape[-1]-1)
                    theta,_=esprit_batched(rx,2,use_eigh=True,sort_doa=False)
                    _,cov_deg2=self.uq(torch.rad2deg(theta),rx,return_covariance=True)
                    cov=cov_deg2*(torch.pi/180)**2
                else:
                    # Exactly the native MultiSubarraysModel tensor convention:
                    # [batch, subarrays=1, repeated_realizations=1, N, T].
                    positions=torch.zeros(batch,1,2,dtype=torch.float32,device=self.device)
                    result=self.model(positions,xx[:,None,None,:,:],None)
                    theta=result['bearings'][:,0]
                    cov=model_output_to_covariance_rad2(result)[:,0]
                preds.append(theta.detach().cpu().numpy().astype(float))
                covs.append(cov.detach().cpu().numpy().astype(float))
        return np.concatenate(preds),np.concatenate(covs)
